"""Build the two finals executables: one onefile .exe per model, plus config.json.

    python scripts/build_exe.py                 # both models
    python scripts/build_exe.py --model 1       # just the main model
    python scripts/build_exe.py --skip-smoke    # build only, don't run smoke_exe.py

WHY ONEFILE (COMPETITION_RULES.md Sec 7.1 / F75). Each submission ZIP holds **exactly two files
at its root** -- `<name>.exe` plus an optional `config.json` -- and README, source, and
라이브러리 폴더 are all explicitly banned. So a PyInstaller *onedir* bundle is not merely
discouraged, it is non-compliant: the three DLLs, both Rule XMLs, `aircraft/` and `engine/` have
to live INSIDE the executable.

THE BUNDLE LAYOUT IS LEGISLATED BY THE C++ SIDE, NOT CHOSEN. `CPPBehaviorTree.cpp:142` loads
`Rule_forTraining.xml` from **the DLL's own directory** (`GetThisModuleDirectory()`), by a
hardcoded filename, ignoring the working directory entirely -- JSBSim chdir()s away, so it has to.
`JSBSimWrapper.py:73-77` loads `JSBSimAIPLib.dll` from its own directory at import time, and
`:118` reads `aircraft/<f>/<f>_init.xml` from there too. Every one of those resolves to the root
of the unpacked bundle, so this script mirrors `Release/` at that root and nothing needs patching.
The one lookup that could NOT be satisfied by layout is `native_bt.py:99`'s four-level `__file__`
walk; `student/runtime_paths.py` handles it by passing an absolute DLL path instead.

BUILD `--console`, AND THAT IS NOT COSMETIC (F70). If the Rule XML is missing or malformed,
`CPPBehaviorTree.cpp:143-148` CATCHES the exception, prints one line to C++ `std::cout`, and sets
`bInitialized=false`. `Step()` then returns a zero-initialised `ControlValue` -- stick and
throttle all zero -- while the client still handshakes and answers at 60 Hz. Nothing raises,
nothing logs on the Python side, and a healthy-looking match is flown with the stick centred. That
one `std::cout` line is the ONLY evidence, and a windowed build throws it away.

EXCLUDE ray/torch DELIBERATELY. The live path imports neither at runtime -- every `ray` import in
`rllib_utils.py` is function-local and `BUNDLE_DIR is None` guards the torch path -- but
PyInstaller's static analyser still FOLLOWS `rllib_utils.py:35` and would pull in multi-GB of
wheels. The excludes are what keep the artifact small; they are not optional hygiene.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent                       # DogFightEnv/Release
_OUT = _ROOT.parent / "submission_exe"     # outside Release/, so no protected asset is shadowed
_BUILD = _OUT / "_build"

sys.path.insert(0, str(_ROOT))
from student.my_submission import SUBMISSION_NAME, TEAM_NAME  # noqa: E402
from student.runtime_paths import DEFAULT_SERVER_IP, DEFAULT_SERVER_PORT  # noqa: E402

# Everything that must sit at the bundle root, mirroring Release/. Sources are relative to _ROOT.
# `PROTECTED` in package_release.py is the same list from the rules' side; this is the runtime's.
_BINARIES = ("AIP_BASE.dll", "AIP_BASE_target.dll", "JSBSimAIPLib.dll")
_DATA_FILES = ("Rule_forTraining.xml", "Rule.xml", "Rule_real_eagle.xml")
_DATA_DIRS = ("aircraft", "engine")
_SCRIPT_XML = ("f15_cruise.xml", "f16_cruise.xml", "fa50_cruise.xml")

# Followed by PyInstaller's static analyser but never reached at runtime. See the docstring.
_EXCLUDES = ("ray", "torch", "tensorflow", "tensorboard", "matplotlib", "pandas", "IPython",
             "notebook", "PIL", "cv2", "sklearn", "scipy")

# Imported by name at runtime, so the analyser cannot see them.
_HIDDEN = ("student.my_observation_v2", "student.my_observation", "pymap3d", "filelock", "yaml")

# One shim per model. The head-on exe cannot receive environment variables -- an operator
# double-clicks it -- so the two values that distinguish it are baked in here. `setdefault`
# rather than assignment so an operator CAN still override on the day if something is wrong.
_SHIM = '''\
"""Generated by scripts/build_exe.py -- do not edit, it is overwritten every build."""
import os
os.environ.setdefault("DOGFIGHT_MODEL_PROFILE", "{profile}")
os.environ.setdefault("DOGFIGHT_TEAM_NAME", "{team}")
from student.my_submission import main
main()
'''


def _variants(models: list[int]) -> list[dict]:
    out = []
    for m in models:
        headon = (m == 2)
        out.append({
            "model": m,
            # Filename English (rules: the "use English" clause governs FILENAMES only),
            # displayed team name Korean with `_HeadOn` as a SUFFIX (`HeadOn_X` is rejected).
            "exe": f"{SUBMISSION_NAME}_headon" if headon else SUBMISSION_NAME,
            "team": f"{TEAM_NAME}_HeadOn" if headon else TEAM_NAME,
            "profile": "2" if headon else "1",
        })
    return out


def _add_data_args() -> list[str]:
    args: list[str] = []
    for name in _BINARIES:
        src = _ROOT / name
        if not src.is_file():
            raise SystemExit(f"missing runtime binary: {src}")
        args += ["--add-binary", f"{src}{os.pathsep}."]
    for name in _DATA_FILES:
        src = _ROOT / name
        if not src.is_file():
            raise SystemExit(f"missing runtime data file: {src}")
        args += ["--add-data", f"{src}{os.pathsep}."]
    for name in _DATA_DIRS:
        src = _ROOT / name
        if not src.is_dir():
            raise SystemExit(f"missing runtime data dir: {src}")
        args += ["--add-data", f"{src}{os.pathsep}{name}"]
    for name in _SCRIPT_XML:
        src = _HERE / name
        if src.is_file():
            args += ["--add-data", f"{src}{os.pathsep}scripts"]
    return args


def _build_env() -> dict:
    """PyInstaller's environment, with the conda env's DLL directory on PATH.

    WHY. In a conda environment the C extensions in `DLLs/` link against DLLs that live in
    `<env>/Library/bin`, which is on PATH only inside an *activated* shell. PyInstaller resolves
    binary dependencies by searching PATH, so building from a non-activated interpreter produces:

        WARNING: Library not found: could not resolve 'ffi.dll', dependency of '..._ctypes.pyd'

    -- a WARNING, and the build then succeeds. The exe it produces dies on launch with
    `ImportError: DLL load failed while importing _ctypes`, because `_ctypes` is what `ctypes`
    needs and `ctypes` is how this project loads all three of its DLLs. Same story for
    `liblzma.dll`, `LIBBZ2.dll` and `libexpat.dll`. Putting the directory on PATH lets
    PyInstaller's own resolver find and bundle them, which is better than hand-listing four
    DLLs that would silently go stale the next time the env changes.
    """
    env = dict(os.environ)
    libbin = Path(sys.executable).parent / "Library" / "bin"
    if libbin.is_dir():
        env["PATH"] = str(libbin) + os.pathsep + env.get("PATH", "")
    return env


def build_one(v: dict, shared: list[str]) -> Path:
    shim = _BUILD / f"entry_{v['exe']}.py"
    shim.write_text(_SHIM.format(profile=v["profile"], team=v["team"]), encoding="utf-8")

    cmd = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
           "--onefile", "--console", "--name", v["exe"],
           "--distpath", str(_OUT), "--workpath", str(_BUILD / "work"),
           "--specpath", str(_BUILD),
           "--paths", str(_ROOT), "--paths", str(_ROOT / "src"),
           *shared, str(shim)]
    print(f"\n[build_exe] model {v['model']} -> {v['exe']}.exe", flush=True)
    subprocess.run(cmd, check=True, env=_build_env())

    exe = _OUT / f"{v['exe']}.exe"
    if not exe.is_file():
        raise SystemExit(f"PyInstaller reported success but {exe} is missing")
    print(f"[build_exe] {exe.name}  {exe.stat().st_size / 1e6:.1f} MB")
    return exe


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--model", type=int, choices=(1, 2), action="append",
                   help="build only this model (repeatable); default builds both")
    p.add_argument("--skip-smoke", action="store_true",
                   help="skip scripts/smoke_exe.py. The smoke test is the ONLY thing that "
                        "distinguishes a working exe from one flying all-zero commands -- "
                        "skip it while iterating, never before packaging.")
    args = p.parse_args()

    _BUILD.mkdir(parents=True, exist_ok=True)

    # config.json ships beside the exe, NOT inside it (it is the ZIP's second file).
    cfg = {"ip": DEFAULT_SERVER_IP, "port": DEFAULT_SERVER_PORT}
    (_OUT / "config.json").write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    print(f"[build_exe] config.json -> {cfg}")

    shared = _add_data_args()
    for mod in _EXCLUDES:
        shared += ["--exclude-module", mod]
    for mod in _HIDDEN:
        shared += ["--hidden-import", mod]

    built = [build_one(v, shared) for v in _variants(sorted(set(args.model or (1, 2))))]

    if args.skip_smoke:
        print("\n[build_exe] smoke test SKIPPED -- do not package on this.")
        return
    for exe in built:
        print(f"\n[build_exe] smoke: {exe.name}", flush=True)
        rc = subprocess.run([sys.executable, str(_HERE / "smoke_exe.py"), str(exe)]).returncode
        if rc != 0:
            raise SystemExit(f"SMOKE FAILED for {exe.name} (rc={rc}) -- do not package this build")
    print("\n[build_exe] all builds passed smoke.")


if __name__ == "__main__":
    main()
